### ISSUE TITLE
6805/HC08/S08/etc in use today?

### ISSUE THREAD

**Issue by larsbrinkhoff** [forthnutter/6805#1]
Hello,

Since you made this 6805 emulator, so you have any sense of whether the family is in use today?  I almost never hear it mentioned in hobbyist settings, it's all AVR, PIC, ARM, 8051 and maybe the odd duckling.

(I'm not sure how they all relate exactly, but my impression is that HC11/12 is a separate family, and HC16 yet another thing.)

**Comment by forthnutter** [comment]
Yes you are correct, do not see the 6805 much now days.
This project started because I had PCB with 68HC05P3 on it. I had S-Record file but didn't have source.
I wanted to reverse engineer it to update it to more modern controller.
I kind of stopped due to loss of interest.
Also I was learning about Factor at the time, thought I will make a emulator.

**Comment by larsbrinkhoff** [comment]
Thanks.  How about the modern incarnations S08 or RS08?  They are still available from e.g. DigiKey, but I'm not sure if they're on the way out or not?

**Comment by forthnutter** [comment]
Yes that might be good direction to go

**Comment by larsbrinkhoff** [comment]
Thanks.
